version: '3.7'

services:

  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
    - ./config/custom.conf:/etc/postgresql/postgresql.conf
    - ./config/database.sql:/docker-entrypoint-initdb.d/database.sql
    - ./data:/var/lib/postgresql/data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
